### ISSUE TITLE
Possible App Store release?

### ISSUE THREAD

**Issue by bastilimbach** [leonspok/Irvue-Screensaver#2]
Are you planning on bringing this screensaver to the Apple App Store like you did with [Irvue](https://itunes.apple.com/app/irvue-unsplash-wallpapers/id1039633667)? Would be much easier to update etc.

**Comment by leonspok** [comment]
As I know, Mac App Store doesn't support native screensavers (with .saver extension).

**Comment by bastilimbach** [comment]
Oh [you're right](https://discussions.apple.com/thread/2726095?start=0&tstart=0). Too bad.
