### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by bsdahl** [leonspok/Irvue-Screensaver#9]
It stopped working for me this week. I just get a blank screen. I tested it on a couple computers/networks and I get the same result. I also tried a collection rather than the featured.

I looked in the system console and I see this repeated error for Irvue:

`Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}`

**Comment by alexjulien** [comment]
Same here. Any way I can help pinpointing it? Irvue, which I also have installed, works fine.

**Comment by lukastison** [comment]
Same here. High Sierra 10.13.4. Just a black screen.

**Comment by leonspok** [comment]
Irvue Screensaver stopped working because its Unsplash API keys were deleted. I updated keys and uploaded new build for v1.0.7.
